### ISSUE TITLE
Could you please provide you code shown in link

### ISSUE THREAD

**Issue by pashtika** [pgrimard/boot-angular-starter#1]
Could you please provide you code shown in link http://patrickgrimard.com/2014/05/16/pagination-with-spring-data-and-hateoas-in-an-angularjs-app/#comment-1264?

I am looking to developed pagination using HATEOAS and Resource and Assembler classes. Pls help

**Comment by pgrimard** [comment]
I don't have a repository you can download from.  That blog post was based on a client project which I cannot make public.
